meta_product_name: "Educity"
meta_title: "Product name -  Adding accountability through community"
meta_description: " Connect with individuals interested in the same course so you can study together through the platform"
meta_image: "cover.png"
twitter_account: "@product_twitter_account"
